name: ml-project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - jupyter
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - pip
  - pip:
      - xgboost
      - lightgbm
      - catboost
      - shap
